### ISSUE TITLE
Nộp bài

### ISSUE THREAD

**Issue by long199941hp** [UET-INT2204-11-fall-18/lab01-long199941hp#1]
Họ tên: Đồng Ngọc Long
Nhóm 1
Cách code
Email: dongngoclong@gmail.com
@tuantmtb

**Comment by tuantmtb** [comment]
điền thêm mã SV nhé em

**Comment by long199941hp** [comment]
Vâng ah

Vào 15:53 Th 6, 07 thg 9 2018 Trần Minh Tuấn <notifications@github.com> đã
viết:
